name: wplando2
recipe: wordpress
config:
  php: '7.4'
  via: apache
  webroot: web
  database: mysql
  xdebug: true
  env_file:
    - .env
proxy:                
  theme:              # Optional: add this if you include the Sage specific config down below
    - localhost:3000
# Add the following if you plan to use Sage as a starter theme
services:
  theme:
    type: node
tooling:
  yarn:
    service: theme